apiVersion: v1
kind: Service
metadata:
  name: service1
  labels: 
    app: nginx-app
spec: 
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - nodePort: 30002
    port: 80
    targetPort: 80

