apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skgadi
  name: nodeport
  labels: 
    app: nginx-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata: 
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nodecont
        image: nginx
        ports:
        - containerPort: 80

